service: aws-node-project
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs18.x

package:
  individually: true
  patterns:
    - "!**"

functions:
  function1:
    handler: index.handler
    package:
      artifact: path/to/artifact.zip 
